### PR TITLE
composer: allow PHP 8

### PR DESCRIPTION
**Pull request by TomasVotruba**
Hi,
I'm trying to update my blog to PHP 8 and these are last packages that block PHP version.

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
You can remove `friendsofphp/php-cs-fixer` as dev dependency

**Comment by TomasVotruba** [comment]
Done :+1:

**Comment by Nielsvanpach** [comment]
Seems fine, thanks @TomasVotruba !

I follow your blog for a couple of years now, keep up the good work 👍

**Comment by Nielsvanpach** [comment]
Release https://github.com/spatie/packagist-api/releases/tag/2.0.2

**Comment by TomasVotruba** [comment]
Amazing, thank you :+1:

**Pull request merged**
