### PR TITLE
V2

### PR DESCRIPTION
**Pull request by markwalet**
As discussed, a proposal for a new version of the packagist client. You can read the changelog for an overview of all changes.

I didn't fix the readme for now.  I'll do that when the interface for the new `PackagistClient` is accepted.

An idea I had just now: Because I'm renaming the `Packagist` class to `PackagistClient`. We could also make this still workable in an `1.*` release. By keeping the old `Packagist` class and deprecating it. Is that something you are interested in?

### CODE REVIEW

**Comment by markwalet** [comment]
Because of this rewrite, I'd like to include myself in the composer authors list. Is that possible?

**Comment by freekmurze** [comment]
Sure!

Could you also update the readme?

**Comment by markwalet** [comment]
Will do that soon ;)

**Comment by markwalet** [comment]
Do I need to include the old client back in?

**Comment by freekmurze** [comment]
Nah, we don't need the old client anymore.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
