### PR TITLE
Update Packagist.php

### PR DESCRIPTION
**Pull request by markwalet**
Make the code in the `Packagist::getPackageMetadata()` method more descriptive.

### CODE REVIEW

**Comment by markwalet** [comment]
About the feedback of StyleCI: I'm not sure if array destructuring is allowed in php 5.5 (lowest supported version for this package), but I just tried to do the same as in the following line: https://github.com/spatie/packagist-api/blob/2af4d1833abfbc6bf517dcfb75bbf4fa208eb93b/src/Packagist.php#L83

**Comment by freekmurze** [comment]
@markwalet feel free to drop support older versions of PHP so you can use the best syntax available.

**Comment by markwalet** [comment]
I saw that Travis now only tests on php version 7.1.

Because newer packages of Spatie are switched over to Github Actions I left out new php version tests on purpose. This can be implemented in a new pull-request, but it is not something I'm planning to do myself.

**Comment by freekmurze** [comment]
Thanks, I'll update the package with our modern standards myself.

**Pull request merged**
